filter:
    excluded_paths: [vendor/*, test/*]

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml ./test/'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'

tools:
    php_analyzer: true
    php_code_coverage: true
