filter:
    excluded_paths: [vendor/*, test/*]

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true

build:
    environment:
        php:
            version: 5.3.23
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml ./test/'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'

tools:
    external_code_coverage:
        timeout: 600
